/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardOrgStructureRouteImport } from './routes/dashboard.org-structure'
import { Route as DashboardBranchesRouteImport } from './routes/dashboard.branches'
import { Route as DashboardPastorsIndexRouteImport } from './routes/dashboard.pastors.index'
import { Route as DashboardPastorsIdRouteImport } from './routes/dashboard.pastors.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgStructureRoute = DashboardOrgStructureRouteImport.update({
  id: '/org-structure',
  path: '/org-structure',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchesRoute = DashboardBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPastorsIndexRoute = DashboardPastorsIndexRouteImport.update({
  id: '/pastors/',
  path: '/pastors/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPastorsIdRoute = DashboardPastorsIdRouteImport.update({
  id: '/pastors/$id',
  path: '/pastors/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/org-structure': typeof DashboardOrgStructureRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pastors/$id': typeof DashboardPastorsIdRoute
  '/dashboard/pastors/': typeof DashboardPastorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/org-structure': typeof DashboardOrgStructureRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pastors/$id': typeof DashboardPastorsIdRoute
  '/dashboard/pastors': typeof DashboardPastorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/org-structure': typeof DashboardOrgStructureRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pastors/$id': typeof DashboardPastorsIdRoute
  '/dashboard/pastors/': typeof DashboardPastorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/branches'
    | '/dashboard/org-structure'
    | '/dashboard/'
    | '/dashboard/pastors/$id'
    | '/dashboard/pastors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/branches'
    | '/dashboard/org-structure'
    | '/dashboard'
    | '/dashboard/pastors/$id'
    | '/dashboard/pastors'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/branches'
    | '/dashboard/org-structure'
    | '/dashboard/'
    | '/dashboard/pastors/$id'
    | '/dashboard/pastors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/org-structure': {
      id: '/dashboard/org-structure'
      path: '/org-structure'
      fullPath: '/dashboard/org-structure'
      preLoaderRoute: typeof DashboardOrgStructureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branches': {
      id: '/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof DashboardBranchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pastors/': {
      id: '/dashboard/pastors/'
      path: '/pastors'
      fullPath: '/dashboard/pastors/'
      preLoaderRoute: typeof DashboardPastorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pastors/$id': {
      id: '/dashboard/pastors/$id'
      path: '/pastors/$id'
      fullPath: '/dashboard/pastors/$id'
      preLoaderRoute: typeof DashboardPastorsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBranchesRoute: typeof DashboardBranchesRoute
  DashboardOrgStructureRoute: typeof DashboardOrgStructureRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPastorsIdRoute: typeof DashboardPastorsIdRoute
  DashboardPastorsIndexRoute: typeof DashboardPastorsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBranchesRoute: DashboardBranchesRoute,
  DashboardOrgStructureRoute: DashboardOrgStructureRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPastorsIdRoute: DashboardPastorsIdRoute,
  DashboardPastorsIndexRoute: DashboardPastorsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
